---
version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: anildoc143/server-image
    container_name: server
    ports:
      - "1111:3000"
    depends_on:
      - db
  
  frontend:
    image: anildoc143/client-image
    container_name: client
    ports:
      - "2222:3000"
    depends_on:
      - backend

volumes:
  db_data:
